//! Bindings for libgphoto2 generated by rust-bindgen

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(feature = "test")]
pub use gphoto2_test as test_utils;
